//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSepatu.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahBahann", Namespace="http://schemas.datacontract.org/2004/07/ServiceSepatu")]
    [System.SerializableAttribute()]
    public partial class TambahBahann : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_BahanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Jenis_BahanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Bahan {
            get {
                return this.ID_BahanField;
            }
            set {
                if ((this.ID_BahanField.Equals(value) != true)) {
                    this.ID_BahanField = value;
                    this.RaisePropertyChanged("ID_Bahan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jenis_Bahan {
            get {
                return this.Jenis_BahanField;
            }
            set {
                if ((object.ReferenceEquals(this.Jenis_BahanField, value) != true)) {
                    this.Jenis_BahanField = value;
                    this.RaisePropertyChanged("Jenis_Bahan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahJenis", Namespace="http://schemas.datacontract.org/2004/07/ServiceSepatu")]
    [System.SerializableAttribute()]
    public partial class TambahJenis : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_JenisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nama_JenisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Jenis {
            get {
                return this.ID_JenisField;
            }
            set {
                if ((this.ID_JenisField.Equals(value) != true)) {
                    this.ID_JenisField = value;
                    this.RaisePropertyChanged("ID_Jenis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama_Jenis {
            get {
                return this.Nama_JenisField;
            }
            set {
                if ((object.ReferenceEquals(this.Nama_JenisField, value) != true)) {
                    this.Nama_JenisField = value;
                    this.RaisePropertyChanged("Nama_Jenis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahMerek", Namespace="http://schemas.datacontract.org/2004/07/ServiceSepatu")]
    [System.SerializableAttribute()]
    public partial class TambahMerek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MerekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nama_MerekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Merek {
            get {
                return this.ID_MerekField;
            }
            set {
                if ((this.ID_MerekField.Equals(value) != true)) {
                    this.ID_MerekField = value;
                    this.RaisePropertyChanged("ID_Merek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nama_Merek {
            get {
                return this.Nama_MerekField;
            }
            set {
                if ((object.ReferenceEquals(this.Nama_MerekField, value) != true)) {
                    this.Nama_MerekField = value;
                    this.RaisePropertyChanged("Nama_Merek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahNota", Namespace="http://schemas.datacontract.org/2004/07/ServiceSepatu")]
    [System.SerializableAttribute()]
    public partial class TambahNota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BulanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JumlahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TahunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanggalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bulan {
            get {
                return this.BulanField;
            }
            set {
                if ((object.ReferenceEquals(this.BulanField, value) != true)) {
                    this.BulanField = value;
                    this.RaisePropertyChanged("Bulan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Nota {
            get {
                return this.ID_NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_NotaField, value) != true)) {
                    this.ID_NotaField = value;
                    this.RaisePropertyChanged("ID_Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jumlah {
            get {
                return this.JumlahField;
            }
            set {
                if ((object.ReferenceEquals(this.JumlahField, value) != true)) {
                    this.JumlahField = value;
                    this.RaisePropertyChanged("Jumlah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tahun {
            get {
                return this.TahunField;
            }
            set {
                if ((object.ReferenceEquals(this.TahunField, value) != true)) {
                    this.TahunField = value;
                    this.RaisePropertyChanged("Tahun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tanggal {
            get {
                return this.TanggalField;
            }
            set {
                if ((object.ReferenceEquals(this.TanggalField, value) != true)) {
                    this.TanggalField = value;
                    this.RaisePropertyChanged("Tanggal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahUkuran", Namespace="http://schemas.datacontract.org/2004/07/ServiceSepatu")]
    [System.SerializableAttribute()]
    public partial class TambahUkuran : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_UkuranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UkuranField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Ukuran {
            get {
                return this.ID_UkuranField;
            }
            set {
                if ((this.ID_UkuranField.Equals(value) != true)) {
                    this.ID_UkuranField = value;
                    this.RaisePropertyChanged("ID_Ukuran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ukuran {
            get {
                return this.UkuranField;
            }
            set {
                if ((object.ReferenceEquals(this.UkuranField, value) != true)) {
                    this.UkuranField = value;
                    this.RaisePropertyChanged("Ukuran");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TambahWarna", Namespace="http://schemas.datacontract.org/2004/07/ServiceSepatu")]
    [System.SerializableAttribute()]
    public partial class TambahWarna : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_WarnaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarnaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Warna {
            get {
                return this.ID_WarnaField;
            }
            set {
                if ((this.ID_WarnaField.Equals(value) != true)) {
                    this.ID_WarnaField = value;
                    this.RaisePropertyChanged("ID_Warna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warna {
            get {
                return this.WarnaField;
            }
            set {
                if ((object.ReferenceEquals(this.WarnaField, value) != true)) {
                    this.WarnaField = value;
                    this.RaisePropertyChanged("Warna");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISepatu")]
    public interface ISepatu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahBahan", ReplyAction="http://tempuri.org/ISepatu/TambahBahanResponse")]
        string TambahBahan(int ID_Bahan, string Jenis_Bahan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahBahan", ReplyAction="http://tempuri.org/ISepatu/TambahBahanResponse")]
        System.Threading.Tasks.Task<string> TambahBahanAsync(int ID_Bahan, string Jenis_Bahan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahJeniss", ReplyAction="http://tempuri.org/ISepatu/TambahJenissResponse")]
        string TambahJeniss(int ID_Jenis, string Nama_Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahJeniss", ReplyAction="http://tempuri.org/ISepatu/TambahJenissResponse")]
        System.Threading.Tasks.Task<string> TambahJenissAsync(int ID_Jenis, string Nama_Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahMerekk", ReplyAction="http://tempuri.org/ISepatu/TambahMerekkResponse")]
        string TambahMerekk(int ID_Merek, string Nama_Merek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahMerekk", ReplyAction="http://tempuri.org/ISepatu/TambahMerekkResponse")]
        System.Threading.Tasks.Task<string> TambahMerekkAsync(int ID_Merek, string Nama_Merek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahNotaa", ReplyAction="http://tempuri.org/ISepatu/TambahNotaaResponse")]
        string TambahNotaa(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahNotaa", ReplyAction="http://tempuri.org/ISepatu/TambahNotaaResponse")]
        System.Threading.Tasks.Task<string> TambahNotaaAsync(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahUkurann", ReplyAction="http://tempuri.org/ISepatu/TambahUkurannResponse")]
        string TambahUkurann(int ID_Ukuran, string Ukuran);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahUkurann", ReplyAction="http://tempuri.org/ISepatu/TambahUkurannResponse")]
        System.Threading.Tasks.Task<string> TambahUkurannAsync(int ID_Ukuran, string Ukuran);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahWarnaa", ReplyAction="http://tempuri.org/ISepatu/TambahWarnaaResponse")]
        string TambahWarnaa(int ID_Warna, string Warna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/TambahWarnaa", ReplyAction="http://tempuri.org/ISepatu/TambahWarnaaResponse")]
        System.Threading.Tasks.Task<string> TambahWarnaaAsync(int ID_Warna, string Warna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editBahan", ReplyAction="http://tempuri.org/ISepatu/editBahanResponse")]
        string editBahan(int ID_Bahan, string Jenis_Bahan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editBahan", ReplyAction="http://tempuri.org/ISepatu/editBahanResponse")]
        System.Threading.Tasks.Task<string> editBahanAsync(int ID_Bahan, string Jenis_Bahan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editJenis", ReplyAction="http://tempuri.org/ISepatu/editJenisResponse")]
        string editJenis(int ID_Jenis, string Nama_Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editJenis", ReplyAction="http://tempuri.org/ISepatu/editJenisResponse")]
        System.Threading.Tasks.Task<string> editJenisAsync(int ID_Jenis, string Nama_Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editMerek", ReplyAction="http://tempuri.org/ISepatu/editMerekResponse")]
        string editMerek(int ID_Merek, string Nama_Merek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editMerek", ReplyAction="http://tempuri.org/ISepatu/editMerekResponse")]
        System.Threading.Tasks.Task<string> editMerekAsync(int ID_Merek, string Nama_Merek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editNota", ReplyAction="http://tempuri.org/ISepatu/editNotaResponse")]
        string editNota(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editNota", ReplyAction="http://tempuri.org/ISepatu/editNotaResponse")]
        System.Threading.Tasks.Task<string> editNotaAsync(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editUkuran", ReplyAction="http://tempuri.org/ISepatu/editUkuranResponse")]
        string editUkuran(int ID_Ukuran, string Ukuran);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editUkuran", ReplyAction="http://tempuri.org/ISepatu/editUkuranResponse")]
        System.Threading.Tasks.Task<string> editUkuranAsync(int ID_Ukuran, string Ukuran);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editWarna", ReplyAction="http://tempuri.org/ISepatu/editWarnaResponse")]
        string editWarna(int ID_Warna, string Warna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/editWarna", ReplyAction="http://tempuri.org/ISepatu/editWarnaResponse")]
        System.Threading.Tasks.Task<string> editWarnaAsync(int ID_Warna, string Warna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteBahan", ReplyAction="http://tempuri.org/ISepatu/deleteBahanResponse")]
        string deleteBahan(int ID_Bahan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteBahan", ReplyAction="http://tempuri.org/ISepatu/deleteBahanResponse")]
        System.Threading.Tasks.Task<string> deleteBahanAsync(int ID_Bahan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteJenis", ReplyAction="http://tempuri.org/ISepatu/deleteJenisResponse")]
        string deleteJenis(int ID_Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteJenis", ReplyAction="http://tempuri.org/ISepatu/deleteJenisResponse")]
        System.Threading.Tasks.Task<string> deleteJenisAsync(int ID_Jenis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteMerek", ReplyAction="http://tempuri.org/ISepatu/deleteMerekResponse")]
        string deleteMerek(int ID_Merek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteMerek", ReplyAction="http://tempuri.org/ISepatu/deleteMerekResponse")]
        System.Threading.Tasks.Task<string> deleteMerekAsync(int ID_Merek);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteNota", ReplyAction="http://tempuri.org/ISepatu/deleteNotaResponse")]
        string deleteNota(string ID_Nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteNota", ReplyAction="http://tempuri.org/ISepatu/deleteNotaResponse")]
        System.Threading.Tasks.Task<string> deleteNotaAsync(string ID_Nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteUkuran", ReplyAction="http://tempuri.org/ISepatu/deleteUkuranResponse")]
        string deleteUkuran(int ID_Ukuran);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteUkuran", ReplyAction="http://tempuri.org/ISepatu/deleteUkuranResponse")]
        System.Threading.Tasks.Task<string> deleteUkuranAsync(int ID_Ukuran);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteWarna", ReplyAction="http://tempuri.org/ISepatu/deleteWarnaResponse")]
        string deleteWarna(int ID_Warna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/deleteWarna", ReplyAction="http://tempuri.org/ISepatu/deleteWarnaResponse")]
        System.Threading.Tasks.Task<string> deleteWarnaAsync(int ID_Warna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListBahan", ReplyAction="http://tempuri.org/ISepatu/ListBahanResponse")]
        ClientSepatu.ServiceReference1.TambahBahann[] ListBahan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListBahan", ReplyAction="http://tempuri.org/ISepatu/ListBahanResponse")]
        System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahBahann[]> ListBahanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListJenis", ReplyAction="http://tempuri.org/ISepatu/ListJenisResponse")]
        ClientSepatu.ServiceReference1.TambahJenis[] ListJenis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListJenis", ReplyAction="http://tempuri.org/ISepatu/ListJenisResponse")]
        System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahJenis[]> ListJenisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListMerek", ReplyAction="http://tempuri.org/ISepatu/ListMerekResponse")]
        ClientSepatu.ServiceReference1.TambahMerek[] ListMerek();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListMerek", ReplyAction="http://tempuri.org/ISepatu/ListMerekResponse")]
        System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahMerek[]> ListMerekAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListNota", ReplyAction="http://tempuri.org/ISepatu/ListNotaResponse")]
        ClientSepatu.ServiceReference1.TambahNota[] ListNota();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListNota", ReplyAction="http://tempuri.org/ISepatu/ListNotaResponse")]
        System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahNota[]> ListNotaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListUkuran", ReplyAction="http://tempuri.org/ISepatu/ListUkuranResponse")]
        ClientSepatu.ServiceReference1.TambahUkuran[] ListUkuran();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListUkuran", ReplyAction="http://tempuri.org/ISepatu/ListUkuranResponse")]
        System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahUkuran[]> ListUkuranAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListWarna", ReplyAction="http://tempuri.org/ISepatu/ListWarnaResponse")]
        ClientSepatu.ServiceReference1.TambahWarna[] ListWarna();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISepatu/ListWarna", ReplyAction="http://tempuri.org/ISepatu/ListWarnaResponse")]
        System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahWarna[]> ListWarnaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISepatuChannel : ClientSepatu.ServiceReference1.ISepatu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SepatuClient : System.ServiceModel.ClientBase<ClientSepatu.ServiceReference1.ISepatu>, ClientSepatu.ServiceReference1.ISepatu {
        
        public SepatuClient() {
        }
        
        public SepatuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SepatuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SepatuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SepatuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TambahBahan(int ID_Bahan, string Jenis_Bahan) {
            return base.Channel.TambahBahan(ID_Bahan, Jenis_Bahan);
        }
        
        public System.Threading.Tasks.Task<string> TambahBahanAsync(int ID_Bahan, string Jenis_Bahan) {
            return base.Channel.TambahBahanAsync(ID_Bahan, Jenis_Bahan);
        }
        
        public string TambahJeniss(int ID_Jenis, string Nama_Jenis) {
            return base.Channel.TambahJeniss(ID_Jenis, Nama_Jenis);
        }
        
        public System.Threading.Tasks.Task<string> TambahJenissAsync(int ID_Jenis, string Nama_Jenis) {
            return base.Channel.TambahJenissAsync(ID_Jenis, Nama_Jenis);
        }
        
        public string TambahMerekk(int ID_Merek, string Nama_Merek) {
            return base.Channel.TambahMerekk(ID_Merek, Nama_Merek);
        }
        
        public System.Threading.Tasks.Task<string> TambahMerekkAsync(int ID_Merek, string Nama_Merek) {
            return base.Channel.TambahMerekkAsync(ID_Merek, Nama_Merek);
        }
        
        public string TambahNotaa(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah) {
            return base.Channel.TambahNotaa(ID_Nota, Tanggal, Bulan, Tahun, Jumlah);
        }
        
        public System.Threading.Tasks.Task<string> TambahNotaaAsync(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah) {
            return base.Channel.TambahNotaaAsync(ID_Nota, Tanggal, Bulan, Tahun, Jumlah);
        }
        
        public string TambahUkurann(int ID_Ukuran, string Ukuran) {
            return base.Channel.TambahUkurann(ID_Ukuran, Ukuran);
        }
        
        public System.Threading.Tasks.Task<string> TambahUkurannAsync(int ID_Ukuran, string Ukuran) {
            return base.Channel.TambahUkurannAsync(ID_Ukuran, Ukuran);
        }
        
        public string TambahWarnaa(int ID_Warna, string Warna) {
            return base.Channel.TambahWarnaa(ID_Warna, Warna);
        }
        
        public System.Threading.Tasks.Task<string> TambahWarnaaAsync(int ID_Warna, string Warna) {
            return base.Channel.TambahWarnaaAsync(ID_Warna, Warna);
        }
        
        public string editBahan(int ID_Bahan, string Jenis_Bahan) {
            return base.Channel.editBahan(ID_Bahan, Jenis_Bahan);
        }
        
        public System.Threading.Tasks.Task<string> editBahanAsync(int ID_Bahan, string Jenis_Bahan) {
            return base.Channel.editBahanAsync(ID_Bahan, Jenis_Bahan);
        }
        
        public string editJenis(int ID_Jenis, string Nama_Jenis) {
            return base.Channel.editJenis(ID_Jenis, Nama_Jenis);
        }
        
        public System.Threading.Tasks.Task<string> editJenisAsync(int ID_Jenis, string Nama_Jenis) {
            return base.Channel.editJenisAsync(ID_Jenis, Nama_Jenis);
        }
        
        public string editMerek(int ID_Merek, string Nama_Merek) {
            return base.Channel.editMerek(ID_Merek, Nama_Merek);
        }
        
        public System.Threading.Tasks.Task<string> editMerekAsync(int ID_Merek, string Nama_Merek) {
            return base.Channel.editMerekAsync(ID_Merek, Nama_Merek);
        }
        
        public string editNota(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah) {
            return base.Channel.editNota(ID_Nota, Tanggal, Bulan, Tahun, Jumlah);
        }
        
        public System.Threading.Tasks.Task<string> editNotaAsync(string ID_Nota, string Tanggal, string Bulan, string Tahun, string Jumlah) {
            return base.Channel.editNotaAsync(ID_Nota, Tanggal, Bulan, Tahun, Jumlah);
        }
        
        public string editUkuran(int ID_Ukuran, string Ukuran) {
            return base.Channel.editUkuran(ID_Ukuran, Ukuran);
        }
        
        public System.Threading.Tasks.Task<string> editUkuranAsync(int ID_Ukuran, string Ukuran) {
            return base.Channel.editUkuranAsync(ID_Ukuran, Ukuran);
        }
        
        public string editWarna(int ID_Warna, string Warna) {
            return base.Channel.editWarna(ID_Warna, Warna);
        }
        
        public System.Threading.Tasks.Task<string> editWarnaAsync(int ID_Warna, string Warna) {
            return base.Channel.editWarnaAsync(ID_Warna, Warna);
        }
        
        public string deleteBahan(int ID_Bahan) {
            return base.Channel.deleteBahan(ID_Bahan);
        }
        
        public System.Threading.Tasks.Task<string> deleteBahanAsync(int ID_Bahan) {
            return base.Channel.deleteBahanAsync(ID_Bahan);
        }
        
        public string deleteJenis(int ID_Jenis) {
            return base.Channel.deleteJenis(ID_Jenis);
        }
        
        public System.Threading.Tasks.Task<string> deleteJenisAsync(int ID_Jenis) {
            return base.Channel.deleteJenisAsync(ID_Jenis);
        }
        
        public string deleteMerek(int ID_Merek) {
            return base.Channel.deleteMerek(ID_Merek);
        }
        
        public System.Threading.Tasks.Task<string> deleteMerekAsync(int ID_Merek) {
            return base.Channel.deleteMerekAsync(ID_Merek);
        }
        
        public string deleteNota(string ID_Nota) {
            return base.Channel.deleteNota(ID_Nota);
        }
        
        public System.Threading.Tasks.Task<string> deleteNotaAsync(string ID_Nota) {
            return base.Channel.deleteNotaAsync(ID_Nota);
        }
        
        public string deleteUkuran(int ID_Ukuran) {
            return base.Channel.deleteUkuran(ID_Ukuran);
        }
        
        public System.Threading.Tasks.Task<string> deleteUkuranAsync(int ID_Ukuran) {
            return base.Channel.deleteUkuranAsync(ID_Ukuran);
        }
        
        public string deleteWarna(int ID_Warna) {
            return base.Channel.deleteWarna(ID_Warna);
        }
        
        public System.Threading.Tasks.Task<string> deleteWarnaAsync(int ID_Warna) {
            return base.Channel.deleteWarnaAsync(ID_Warna);
        }
        
        public ClientSepatu.ServiceReference1.TambahBahann[] ListBahan() {
            return base.Channel.ListBahan();
        }
        
        public System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahBahann[]> ListBahanAsync() {
            return base.Channel.ListBahanAsync();
        }
        
        public ClientSepatu.ServiceReference1.TambahJenis[] ListJenis() {
            return base.Channel.ListJenis();
        }
        
        public System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahJenis[]> ListJenisAsync() {
            return base.Channel.ListJenisAsync();
        }
        
        public ClientSepatu.ServiceReference1.TambahMerek[] ListMerek() {
            return base.Channel.ListMerek();
        }
        
        public System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahMerek[]> ListMerekAsync() {
            return base.Channel.ListMerekAsync();
        }
        
        public ClientSepatu.ServiceReference1.TambahNota[] ListNota() {
            return base.Channel.ListNota();
        }
        
        public System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahNota[]> ListNotaAsync() {
            return base.Channel.ListNotaAsync();
        }
        
        public ClientSepatu.ServiceReference1.TambahUkuran[] ListUkuran() {
            return base.Channel.ListUkuran();
        }
        
        public System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahUkuran[]> ListUkuranAsync() {
            return base.Channel.ListUkuranAsync();
        }
        
        public ClientSepatu.ServiceReference1.TambahWarna[] ListWarna() {
            return base.Channel.ListWarna();
        }
        
        public System.Threading.Tasks.Task<ClientSepatu.ServiceReference1.TambahWarna[]> ListWarnaAsync() {
            return base.Channel.ListWarnaAsync();
        }
    }
}
